version: "3.3"
services:
  db:
    container_name: db
    image: postgres:14.6-alpine
    restart: always
    env_file:
      - ../.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    container_name: redis
    image: redis:7.0.11-alpine
    restart: always

  back:
    container_name: back
    build: ../backend
    restart: always
    env_file:
      - ../.env
    volumes:
      - static_dir:/app/static/
      - media_dir:/app/media/
    depends_on:
      - db
      - redis
    environment:
      - DOCKER=True

  front:
    container_name: front
    build: ../frontend
    restart: always

  nginx:
    container_name: nginx
    build: ../nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - static_dir:/etc/nginx/html/static/
      - media_dir:/etc/nginx/html/media/
    depends_on:
      - back
      - front

volumes:
  static_dir:
  media_dir:
  postgres_data:
