version: "3.3"
services:
  db:
    container_name: db
    image: postgres:14.6-alpine
    restart: always
    env_file:
      - ../.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    container_name: redis
    image: redis:7.0.11-alpine
    restart: always

  backend:
    container_name: backend
    build: ../backend
    restart: always
    expose:
      - "8000"
    env_file:
      - ../.env
    volumes:
      - static_dir:/app/static/
      - media_dir:/app/media/
    depends_on:
      - db
      - redis
    environment:
      - DOCKER=True

  frontend:
    container_name: frontend
    build: ../frontend
    restart: always
    expose:
      - "3000"

  admin_product:
    container_name: admin_product
    build: ../admin
    restart: always
    expose:
      - "3050"

  nginx:
    container_name: nginx
    build: ../nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - static_dir:/etc/nginx/html/static/
      - media_dir:/etc/nginx/html/media/
    depends_on:
      - backend
      - frontend

volumes:
  static_dir:
  media_dir:
  postgres_data:
