# Generated by Django 4.2.2 on 2024-02-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('text_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID текста')),
                ('name', models.TextField(max_length=300, verbose_name='Название текста')),
                ('text', models.TextField(max_length=300, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Текст',
                'verbose_name_plural': 'Тексты',
            },
        ),
    ]
